# mode
application:
  profiles:
    active: dev

# ---------- devtools
spring.devtools.restart.enabled: true

# ---------- actuators
management.endpoints.web.exposure.include: "*"
#management.endpoints.web.exposure.exclude: "*"


# ---------- scheduler
# scheduler interface
scheduler:
  schedulerInstances:
    - name: "syncResourcesGatherer"
      className: "io.dkargo.hub.centercity.sync.worker.SyncResourcesGatherer"
      dynamicDelay: false
      cron: 5 * * * * *
#      delay: 5000 # scheduled delay, when isDynamicDelay is true then it is max value, unit: milliseconds
#    - name: "syncResourcesTplDemon"
#      className: "io.dkargo.hub.centercity.sync.worker.SyncResourcesTplDemon"
#      dynamicDelay: false
#      delay: 5000
#    - name: "syncResourcesDisposer"
#      className: "io.dkargo.hub.centercity.sync.worker.SyncResourcesDisposer"
#      dynamicDelay: false
#      delay: 5000